"""fixed book tables

Revision ID: aca5565cfdc6
Revises: ad2b3b4b66cd
Create Date: 2026-02-01 03:28:21.845974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca5565cfdc6'
down_revision: Union[str, Sequence[str], None] = 'ad2b3b4b66cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('book_authors_author_id_fkey'), 'book_authors', type_='foreignkey')
    op.drop_constraint(op.f('book_authors_book_id_fkey'), 'book_authors', type_='foreignkey')
    op.create_foreign_key(None, 'book_authors', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_authors', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('book_genres_book_id_fkey'), 'book_genres', type_='foreignkey')
    op.drop_constraint(op.f('book_genres_genre_id_fkey'), 'book_genres', type_='foreignkey')
    op.create_foreign_key(None, 'book_genres', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('books_title_key'), 'books', type_='unique')
    op.drop_constraint(op.f('user_books_book_id_fkey'), 'user_books', type_='foreignkey')
    op.drop_constraint(op.f('user_books_user_id_fkey'), 'user_books', type_='foreignkey')
    op.create_foreign_key(None, 'user_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_books', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_books', type_='foreignkey')
    op.drop_constraint(None, 'user_books', type_='foreignkey')
    op.create_foreign_key(op.f('user_books_user_id_fkey'), 'user_books', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_books_book_id_fkey'), 'user_books', 'books', ['book_id'], ['id'])
    op.create_unique_constraint(op.f('books_title_key'), 'books', ['title'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'book_genres', type_='foreignkey')
    op.drop_constraint(None, 'book_genres', type_='foreignkey')
    op.create_foreign_key(op.f('book_genres_genre_id_fkey'), 'book_genres', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key(op.f('book_genres_book_id_fkey'), 'book_genres', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'book_authors', type_='foreignkey')
    op.drop_constraint(None, 'book_authors', type_='foreignkey')
    op.create_foreign_key(op.f('book_authors_book_id_fkey'), 'book_authors', 'books', ['book_id'], ['id'])
    op.create_foreign_key(op.f('book_authors_author_id_fkey'), 'book_authors', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
